language: ruby

before_script:
  - psql -c 'create database love_learn_test;' -U postgres

services:
  - postgresql

deploy:
  provider: heroku
  api_key:
    secure: UmmsecjrVSQq9e3wfM28HGa+hG01knSj0zijtnee6vMrwAgfCXBTFuoktg4uF562BMkdciYG8wK6YbkWf2hA9HkFpIJlF1iNT2tZXEqgdT5jhjVCnzNzNOAjXOPD9s0oheb4ngoy0VcLXtvqK4Bo01Qo23NzGf9TOIzelYL3WzDFbqpuintxNdqA8HWyOx0xxnDU0wJjQlYa0MoUeGkbngUt2t4c+8XY9J3+JhGnvv7nZnX8AyQAPOyLafJmXiOlqm5ELgUnnblogtBk4KhA/KeNFjMPH7oDRJYo6g05LDf8dGjDPNCEJnBlXfwMOahD6yRnAYsQwCx4h2HfG1o3row09yeN8zl0vRK667ksWivWWmbueAD1IkrR9hWH8rUCT+X/XuoW8jM34mkNWrF5DXPTsIL0iDKket7FrP/eDLKSCRwmrGpaWDFpX45OwX2m13DYfN1hiG6dPhYf/QITABaSfuNbkfiChUJyDrzy2/VdoIAdqKfBPvJxot8z5qpx+Y5uripdovtNCr9N99TGXFY1DWENOau6rm1Jc0K0FkYMIowUDwAOukesXnLMYjru7b4ETWPCi30MwWsyDYKVrWEy78Je4YWaZBtakk+1xZxw/Xeq9N5DnIN1XSpbX4DLstPJGrKEZmzkfgBjaBFDMkuH87fcMIEPbr+DEWBumEs=
  app:
    master: lovelearn
  run:
    - "rake db:migrate"
